{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "eaa4f3f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import libraries\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from tensorflow import keras\n",
    "from matplotlib import pyplot as plt\n",
    "%matplotlib inline\n",
    "import seaborn as sns\n",
    "\n",
    "from keras.layers import Dense\n",
    "from keras.models import Sequential\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from sklearn.metrics import classification_report\n",
    "from sklearn.metrics import confusion_matrix\n",
    "\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn import svm\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.gaussian_process import GaussianProcessClassifier\n",
    "from sklearn.tree import DecisionTreeClassifier, export_graphviz\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "from sklearn.ensemble import AdaBoostClassifier\n",
    "from sklearn.naive_bayes import GaussianNB\n",
    "from sklearn.discriminant_analysis import LinearDiscriminantAnalysis\n",
    "from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1c9c6736",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\utils\\validation.py:72: FutureWarning: Pass priors=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error\n",
      "  \"will result in an error\", FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6682 - accuracy: 0.6295\n",
      "17/17 [==============================] - 0s 2ms/step - loss: 0.5891 - accuracy: 0.6808\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6441 - accuracy: 0.6348\n",
      "17/17 [==============================] - 0s 3ms/step - loss: 0.5891 - accuracy: 0.6885\n",
      "147/147 [==============================] - 2s 2ms/step - loss: 0.6596 - accuracy: 0.6440\n",
      "17/17 [==============================] - 0s 3ms/step - loss: 0.5702 - accuracy: 0.7327\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6412 - accuracy: 0.6363\n",
      "17/17 [==============================] - 0s 2ms/step - loss: 0.5791 - accuracy: 0.6827\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6477 - accuracy: 0.6513\n",
      "17/17 [==============================] - 0s 2ms/step - loss: 0.5764 - accuracy: 0.6981\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6643 - accuracy: 0.6735\n",
      "17/17 [==============================] - 0s 2ms/step - loss: 0.5844 - accuracy: 0.7365\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6659 - accuracy: 0.6410\n",
      "17/17 [==============================] - 0s 3ms/step - loss: 0.6134 - accuracy: 0.6558\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6443 - accuracy: 0.6340\n",
      "17/17 [==============================] - 0s 2ms/step - loss: 0.5814 - accuracy: 0.6108\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6406 - accuracy: 0.6496\n",
      "17/17 [==============================] - 0s 2ms/step - loss: 0.5573 - accuracy: 0.6859\n",
      "147/147 [==============================] - 1s 2ms/step - loss: 0.6578 - accuracy: 0.6295\n",
      "17/17 [==============================] - 0s 2ms/step - loss: 0.5827 - accuracy: 0.6763\n",
      "NeuralNet: 0.6848024964332581\n",
      "KNN: 0.7604394545724025\n",
      "SVC: 0.767755669186305\n",
      "DecisionTree: 0.7408118423002816\n",
      "RandomForest: 0.7563976582184675\n",
      "MLP: 0.7610141544390098\n",
      "AdaBoost: nan\n",
      "GaussianNB: nan\n",
      "QuadraticDiscrimination: 0.7279135171187194\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 443, in fit\n",
      "    return super().fit(X, y, sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 117, in fit\n",
      "    self._validate_estimator()\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\ensemble\\_weight_boosting.py\", line 454, in _validate_estimator\n",
      "    \"AdaBoostClassifier with algorithm='SAMME.R' requires \"\n",
      "TypeError: AdaBoostClassifier with algorithm='SAMME.R' requires that the weak learner supports the calculation of class probabilities with a predict_proba method.\n",
      "Please change the base estimator or set algorithm='SAMME' instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 210, in fit\n",
      "    sample_weight=sample_weight)\n",
      "  File \"C:\\Users\\jk452\\anaconda3\\envs\\tf\\lib\\site-packages\\sklearn\\naive_bayes.py\", line 389, in _partial_fit\n",
      "    if len(priors) != n_classes:\n",
      "TypeError: len() of unsized object\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv(\"./Wine Quality/wine.csv\", index_col = \"index\")\n",
    "\n",
    "df['quality'] = df['quality'].apply(lambda x: 1 if x >= 6 else 0)\n",
    "\n",
    "X = df.iloc[:, 0:11]\n",
    "y = df.iloc[:, 11]\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size = 0.20, stratify=y)\n",
    "\n",
    "scaler = StandardScaler().fit(X_train)\n",
    "X_train = scaler.transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "\n",
    "def base_model():\n",
    "    model = Sequential()\n",
    "    model.add(Dense(12, input_shape=(11,), kernel_initializer='normal', activation=\"relu\"))\n",
    "    model.add(Dense(9, kernel_initializer='normal', activation=\"relu\"))\n",
    "    model.add(Dense(1, kernel_initializer='normal', activation=\"sigmoid\"))\n",
    "    model.compile(loss='mse', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "models = []\n",
    "estimator = KerasClassifier(build_fn=base_model, \n",
    "                            nb_epoch=50, verbose=1)\n",
    "models.append(('NeuralNet', estimator))\n",
    "models.append(('KNN', KNeighborsClassifier(3)))\n",
    "models.append(('SVC', SVC(gamma=2, C=1)))\n",
    "models.append(('DecisionTree', DecisionTreeClassifier(max_depth=5)))\n",
    "models.append(('RandomForest', RandomForestClassifier(max_depth=5)))\n",
    "models.append(('MLP', MLPClassifier(alpha=1, max_iter=1000)))\n",
    "models.append(('AdaBoost', AdaBoostClassifier(3)))\n",
    "models.append(('GaussianNB', GaussianNB(3)))\n",
    "models.append(('QuadraticDiscrimination', QuadraticDiscriminantAnalysis()))\n",
    "\n",
    "\n",
    "for name, model in models:\n",
    "    results = cross_val_score(model, X_train, y_train, cv=10)\n",
    "    print(\"{}: {}\".format(name, results.mean()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "452499c5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tf",
   "language": "python",
   "name": "tf"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
